# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from . import node_service_pb2 as node__service__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in node_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NodeServiceStub(object):
    """NodeService: control-plane gRPC interface for ETP node discovery and health.
    Separate from ShardService (data-plane) — each node runs both.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
            "/ltp.node.NodeService/Handshake",
            request_serializer=node__service__pb2.HandshakeRequest.SerializeToString,
            response_deserializer=node__service__pb2.HandshakeResponse.FromString,
            _registered_method=True,
        )
        self.Ping = channel.unary_unary(
            "/ltp.node.NodeService/Ping",
            request_serializer=node__service__pb2.PingRequest.SerializeToString,
            response_deserializer=node__service__pb2.PingResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/ltp.node.NodeService/HealthCheck",
            request_serializer=node__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=node__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.ExchangePeers = channel.unary_unary(
            "/ltp.node.NodeService/ExchangePeers",
            request_serializer=node__service__pb2.PeerExchangeRequest.SerializeToString,
            response_deserializer=node__service__pb2.PeerExchangeResponse.FromString,
            _registered_method=True,
        )


class NodeServiceServicer(object):
    """NodeService: control-plane gRPC interface for ETP node discovery and health.
    Separate from ShardService (data-plane) — each node runs both.
    """

    def Handshake(self, request, context):
        """Post-quantum authenticated handshake between nodes."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Ping(self, request, context):
        """Lightweight liveness check."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Full health status for monitoring and load balancers."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExchangePeers(self, request, context):
        """Gossip-based peer exchange (ML-DSA-65 signed)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Handshake": grpc.unary_unary_rpc_method_handler(
            servicer.Handshake,
            request_deserializer=node__service__pb2.HandshakeRequest.FromString,
            response_serializer=node__service__pb2.HandshakeResponse.SerializeToString,
        ),
        "Ping": grpc.unary_unary_rpc_method_handler(
            servicer.Ping,
            request_deserializer=node__service__pb2.PingRequest.FromString,
            response_serializer=node__service__pb2.PingResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=node__service__pb2.HealthCheckRequest.FromString,
            response_serializer=node__service__pb2.HealthCheckResponse.SerializeToString,
        ),
        "ExchangePeers": grpc.unary_unary_rpc_method_handler(
            servicer.ExchangePeers,
            request_deserializer=node__service__pb2.PeerExchangeRequest.FromString,
            response_serializer=node__service__pb2.PeerExchangeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ltp.node.NodeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ltp.node.NodeService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """NodeService: control-plane gRPC interface for ETP node discovery and health.
    Separate from ShardService (data-plane) — each node runs both.
    """

    @staticmethod
    def Handshake(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.node.NodeService/Handshake",
            node__service__pb2.HandshakeRequest.SerializeToString,
            node__service__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Ping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.node.NodeService/Ping",
            node__service__pb2.PingRequest.SerializeToString,
            node__service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.node.NodeService/HealthCheck",
            node__service__pb2.HealthCheckRequest.SerializeToString,
            node__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExchangePeers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.node.NodeService/ExchangePeers",
            node__service__pb2.PeerExchangeRequest.SerializeToString,
            node__service__pb2.PeerExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
