# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "node_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12node_service.proto\x12\x08ltp.node"E\n\x10HandshakeRequest\x12\x17\n\x0fsigned_envelope\x18\x01 \x01(\x0c\x12\x18\n\x10protocol_version\x18\x02 \x01(\r"U\n\x11HandshakeResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x17\n\x0fsigned_envelope\x18\x02 \x01(\x0c\x12\x15\n\rreject_reason\x18\x03 \x01(\t"%\n\x0bPingRequest\x12\x16\n\x0esender_node_id\x18\x01 \x01(\t"2\n\x0cPingResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01"\x14\n\x12HealthCheckRequest"\xa1\x01\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x01\x12\x12\n\npeer_count\x18\x05 \x01(\x05\x12\x13\n\x0bshard_count\x18\x06 \x01(\x03\x12\x18\n\x10protocol_version\x18\x07 \x01(\r"m\n\x13PeerExchangeRequest\x12\x16\n\x0esigned_message\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x11\n\tsender_vk\x18\x03 \x01(\x0c\x12\x18\n\x10protocol_version\x18\x04 \x01(\r"\x97\x01\n\x14PeerExchangeResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0esigned_message\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x11\n\tsender_vk\x18\x04 \x01(\x0c\x12\x15\n\rreject_reason\x18\x05 \x01(\t\x12\x18\n\x10peers_discovered\x18\x06 \x01(\x05\x32\xa6\x02\n\x0bNodeService\x12\x44\n\tHandshake\x12\x1a.ltp.node.HandshakeRequest\x1a\x1b.ltp.node.HandshakeResponse\x12\x35\n\x04Ping\x12\x15.ltp.node.PingRequest\x1a\x16.ltp.node.PingResponse\x12J\n\x0bHealthCheck\x12\x1c.ltp.node.HealthCheckRequest\x1a\x1d.ltp.node.HealthCheckResponse\x12N\n\rExchangePeers\x12\x1d.ltp.node.PeerExchangeRequest\x1a\x1e.ltp.node.PeerExchangeResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "node_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HANDSHAKEREQUEST"]._serialized_start = 32
    _globals["_HANDSHAKEREQUEST"]._serialized_end = 101
    _globals["_HANDSHAKERESPONSE"]._serialized_start = 103
    _globals["_HANDSHAKERESPONSE"]._serialized_end = 188
    _globals["_PINGREQUEST"]._serialized_start = 190
    _globals["_PINGREQUEST"]._serialized_end = 227
    _globals["_PINGRESPONSE"]._serialized_start = 229
    _globals["_PINGRESPONSE"]._serialized_end = 279
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 281
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 301
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 304
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 465
    _globals["_PEEREXCHANGEREQUEST"]._serialized_start = 467
    _globals["_PEEREXCHANGEREQUEST"]._serialized_end = 576
    _globals["_PEEREXCHANGERESPONSE"]._serialized_start = 579
    _globals["_PEEREXCHANGERESPONSE"]._serialized_end = 730
    _globals["_NODESERVICE"]._serialized_start = 733
    _globals["_NODESERVICE"]._serialized_end = 1027
# @@protoc_insertion_point(module_scope)
