# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shard_service_pb2 as shard__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shard_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardServiceStub(object):
    """ShardService: gRPC interface for commitment node operations.
    Each commitment node runs a ShardService server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreShard = channel.unary_unary(
                '/ltp.shard.ShardService/StoreShard',
                request_serializer=shard__service__pb2.StoreShardRequest.SerializeToString,
                response_deserializer=shard__service__pb2.StoreShardResponse.FromString,
                _registered_method=True)
        self.FetchShard = channel.unary_unary(
                '/ltp.shard.ShardService/FetchShard',
                request_serializer=shard__service__pb2.FetchShardRequest.SerializeToString,
                response_deserializer=shard__service__pb2.FetchShardResponse.FromString,
                _registered_method=True)
        self.AuditChallenge = channel.unary_unary(
                '/ltp.shard.ShardService/AuditChallenge',
                request_serializer=shard__service__pb2.AuditChallengeRequest.SerializeToString,
                response_deserializer=shard__service__pb2.AuditChallengeResponse.FromString,
                _registered_method=True)
        self.RemoveShard = channel.unary_unary(
                '/ltp.shard.ShardService/RemoveShard',
                request_serializer=shard__service__pb2.RemoveShardRequest.SerializeToString,
                response_deserializer=shard__service__pb2.RemoveShardResponse.FromString,
                _registered_method=True)
        self.GetNodeInfo = channel.unary_unary(
                '/ltp.shard.ShardService/GetNodeInfo',
                request_serializer=shard__service__pb2.NodeInfoRequest.SerializeToString,
                response_deserializer=shard__service__pb2.NodeInfoResponse.FromString,
                _registered_method=True)
        self.StoreShardsStream = channel.stream_unary(
                '/ltp.shard.ShardService/StoreShardsStream',
                request_serializer=shard__service__pb2.StoreShardRequest.SerializeToString,
                response_deserializer=shard__service__pb2.StoreShardsStreamResponse.FromString,
                _registered_method=True)
        self.FetchShardsBatch = channel.unary_unary(
                '/ltp.shard.ShardService/FetchShardsBatch',
                request_serializer=shard__service__pb2.FetchShardsBatchRequest.SerializeToString,
                response_deserializer=shard__service__pb2.FetchShardsBatchResponse.FromString,
                _registered_method=True)


class ShardServiceServicer(object):
    """ShardService: gRPC interface for commitment node operations.
    Each commitment node runs a ShardService server.
    """

    def StoreShard(self, request, context):
        """Store an encrypted shard on the node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchShard(self, request, context):
        """Fetch an encrypted shard from the node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditChallenge(self, request, context):
        """Respond to a storage-proof audit challenge.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveShard(self, request, context):
        """Remove a shard (used for deletion/eviction).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Get node status (shard count, health, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreShardsStream(self, request_iterator, context):
        """Batch store multiple shards in one call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchShardsBatch(self, request, context):
        """Batch fetch multiple shards.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreShard': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreShard,
                    request_deserializer=shard__service__pb2.StoreShardRequest.FromString,
                    response_serializer=shard__service__pb2.StoreShardResponse.SerializeToString,
            ),
            'FetchShard': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchShard,
                    request_deserializer=shard__service__pb2.FetchShardRequest.FromString,
                    response_serializer=shard__service__pb2.FetchShardResponse.SerializeToString,
            ),
            'AuditChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditChallenge,
                    request_deserializer=shard__service__pb2.AuditChallengeRequest.FromString,
                    response_serializer=shard__service__pb2.AuditChallengeResponse.SerializeToString,
            ),
            'RemoveShard': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveShard,
                    request_deserializer=shard__service__pb2.RemoveShardRequest.FromString,
                    response_serializer=shard__service__pb2.RemoveShardResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=shard__service__pb2.NodeInfoRequest.FromString,
                    response_serializer=shard__service__pb2.NodeInfoResponse.SerializeToString,
            ),
            'StoreShardsStream': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreShardsStream,
                    request_deserializer=shard__service__pb2.StoreShardRequest.FromString,
                    response_serializer=shard__service__pb2.StoreShardsStreamResponse.SerializeToString,
            ),
            'FetchShardsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchShardsBatch,
                    request_deserializer=shard__service__pb2.FetchShardsBatchRequest.FromString,
                    response_serializer=shard__service__pb2.FetchShardsBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ltp.shard.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ltp.shard.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService(object):
    """ShardService: gRPC interface for commitment node operations.
    Each commitment node runs a ShardService server.
    """

    @staticmethod
    def StoreShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/StoreShard',
            shard__service__pb2.StoreShardRequest.SerializeToString,
            shard__service__pb2.StoreShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/FetchShard',
            shard__service__pb2.FetchShardRequest.SerializeToString,
            shard__service__pb2.FetchShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/AuditChallenge',
            shard__service__pb2.AuditChallengeRequest.SerializeToString,
            shard__service__pb2.AuditChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/RemoveShard',
            shard__service__pb2.RemoveShardRequest.SerializeToString,
            shard__service__pb2.RemoveShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/GetNodeInfo',
            shard__service__pb2.NodeInfoRequest.SerializeToString,
            shard__service__pb2.NodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreShardsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ltp.shard.ShardService/StoreShardsStream',
            shard__service__pb2.StoreShardRequest.SerializeToString,
            shard__service__pb2.StoreShardsStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchShardsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ltp.shard.ShardService/FetchShardsBatch',
            shard__service__pb2.FetchShardsBatchRequest.SerializeToString,
            shard__service__pb2.FetchShardsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
