# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from . import transfer_service_pb2 as transfer__service__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in transfer_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TransferServiceStub(object):
    """TransferService: high-level commit/materialize RPCs for cross-node transfers.
    Builds on ShardService (data-plane) and NodeService (control-plane).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitEntity = channel.unary_unary(
            "/ltp.transfer.TransferService/CommitEntity",
            request_serializer=transfer__service__pb2.CommitRequest.SerializeToString,
            response_deserializer=transfer__service__pb2.CommitResponse.FromString,
            _registered_method=True,
        )
        self.MaterializeEntity = channel.unary_unary(
            "/ltp.transfer.TransferService/MaterializeEntity",
            request_serializer=transfer__service__pb2.MaterializeRequest.SerializeToString,
            response_deserializer=transfer__service__pb2.MaterializeResponse.FromString,
            _registered_method=True,
        )


class TransferServiceServicer(object):
    """TransferService: high-level commit/materialize RPCs for cross-node transfers.
    Builds on ShardService (data-plane) and NodeService (control-plane).
    """

    def CommitEntity(self, request, context):
        """Commit an entity: encode, encrypt, distribute shards, return transfer bundle."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MaterializeEntity(self, request, context):
        """Materialize an entity from a transfer bundle."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CommitEntity": grpc.unary_unary_rpc_method_handler(
            servicer.CommitEntity,
            request_deserializer=transfer__service__pb2.CommitRequest.FromString,
            response_serializer=transfer__service__pb2.CommitResponse.SerializeToString,
        ),
        "MaterializeEntity": grpc.unary_unary_rpc_method_handler(
            servicer.MaterializeEntity,
            request_deserializer=transfer__service__pb2.MaterializeRequest.FromString,
            response_serializer=transfer__service__pb2.MaterializeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ltp.transfer.TransferService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ltp.transfer.TransferService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TransferService(object):
    """TransferService: high-level commit/materialize RPCs for cross-node transfers.
    Builds on ShardService (data-plane) and NodeService (control-plane).
    """

    @staticmethod
    def CommitEntity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.transfer.TransferService/CommitEntity",
            transfer__service__pb2.CommitRequest.SerializeToString,
            transfer__service__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MaterializeEntity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ltp.transfer.TransferService/MaterializeEntity",
            transfer__service__pb2.MaterializeRequest.SerializeToString,
            transfer__service__pb2.MaterializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
