#!/usr/bin/env python3
"""Export ``create_etp_alert_rules()`` to a Prometheus-Operator
``PrometheusRule`` manifest.

The Python registry in ``src/ltp/observability/alerts.py`` is the
source of truth for LTP alert definitions. Rather than maintaining
the same rules in YAML, this script renders the Python list into a
``PrometheusRule`` document that the in-cluster Prometheus picks up
via the standard ``rule_files`` discovery from ``kube-prometheus-stack``.

Usage::

    python3 scripts/export_alert_rules.py \\
        > infra/helm/observability/templates/prometheus-rules-generated.yaml

The Helm chart commits the rendered output. Re-render whenever the
Python list changes — a CI check (PR B2) diffs the on-disk file against
a fresh render and fails if they diverge.

Notes
-----
- The Python ``AlertCondition`` enum has an ``ANY_OCCURRENCE`` variant
  that doesn't map to a single PromQL comparison; we render it as
  ``metric > 0`` which matches the in-process ``AlertEvaluator``.
- ``for_seconds`` becomes the PromQL ``for:`` duration.
- Histogram-percentile alerts in the Python list are currently
  count-based simplifications; this script preserves them as-is.
  When the Python side gets proper ``histogram_quantile`` recipes,
  this script becomes a thin pass-through.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Run as a script: make the package importable without installing.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ltp.observability.alerts import AlertCondition, AlertRule, create_etp_alert_rules  # noqa: E402

HEADER = """\
# Auto-generated by scripts/export_alert_rules.py — DO NOT EDIT BY HAND.
# Source of truth: src/ltp/observability/alerts.py :: create_etp_alert_rules()
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ltp-etp-alerts
  labels:
    app.kubernetes.io/name: ltp
    app.kubernetes.io/component: etp
    release: kube-prometheus-stack
spec:
  groups:
    - name: ltp.etp
      rules:
"""


def render_promql(rule: AlertRule) -> str:
    """Render a single AlertRule's condition as a PromQL expression."""
    if rule.condition is AlertCondition.GREATER_THAN:
        return f"{rule.metric_name} > {rule.threshold}"
    if rule.condition is AlertCondition.LESS_THAN:
        return f"{rule.metric_name} < {rule.threshold}"
    if rule.condition is AlertCondition.EQUALS:
        return f"{rule.metric_name} == {rule.threshold}"
    if rule.condition is AlertCondition.ANY_OCCURRENCE:
        return f"{rule.metric_name} > 0"
    raise ValueError(f"Unhandled AlertCondition: {rule.condition!r}")


def render_rule(rule: AlertRule) -> str:
    """Render a single AlertRule as YAML lines under spec.groups[0].rules."""
    expr = render_promql(rule)
    for_duration = f"{int(rule.for_seconds)}s" if rule.for_seconds else "0s"

    return (
        f"        - alert: {rule.name}\n"
        f"          expr: {expr}\n"
        f"          for: {for_duration}\n"
        f"          labels:\n"
        f"            severity: {rule.severity.value}\n"
        f"            component: etp\n"
        f"            source: ltp.observability.alerts.create_etp_alert_rules\n"
        f"          annotations:\n"
        f"            summary: {rule.description!r}\n"
        f"            runbook: https://github.com/GlobalSettlementNetwork/gsx-lattice-protocol/blob/main/docs/OPERATOR_RUNBOOK.md#{rule.name.replace('_', '-')}\n"
    )


def main() -> int:
    rules = create_etp_alert_rules()
    sys.stdout.write(HEADER)
    for rule in rules:
        sys.stdout.write(render_rule(rule))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
